import type { SourceDefinition } from "@/src/lib/types";

export const SOURCE_REGISTRY: SourceDefinition[] = [
  {
    id: "claude-code-changelog",
    competitor: "anthropic",
    label: "Claude Code changelog",
    kind: "official_site",
    cadence: "daily",
    urls: ["https://code.claude.com/docs/en/changelog"],
    monitoring_tier: "primary",
    preferred_fetch_provider: "firecrawl",
    parse_mode: "markdown",
    notes: "Track dated Claude Code releases, workflow changes, model support updates, and developer-facing product shifts.",
  },
  {
    id: "anthropic-news",
    competitor: "anthropic",
    label: "Anthropic official announcements",
    kind: "official_site",
    cadence: "daily",
    urls: ["https://www.anthropic.com/news"],
    monitoring_tier: "secondary",
    parse_mode: "html",
    notes: "Track broader Anthropic launch framing, enterprise positioning, partnerships, and messaging changes.",
  },
  {
    id: "gemini-release-notes",
    competitor: "gemini",
    label: "Gemini release notes",
    kind: "official_site",
    cadence: "daily",
    urls: ["https://gemini.google/release-notes/"],
    monitoring_tier: "primary",
    preferred_fetch_provider: "firecrawl",
    parse_mode: "markdown",
    notes: "Track dated Gemini releases, feature rollouts, availability changes, and packaging updates from the official release-notes surface.",
  },
  {
    id: "gemini-blog",
    competitor: "gemini",
    label: "Google Gemini blog",
    kind: "official_site",
    cadence: "daily",
    urls: ["https://blog.google/products/gemini/"],
    monitoring_tier: "secondary",
    parse_mode: "html",
    notes: "Track broader Gemini launches, integrations, and messaging changes from the public Google blog.",
  },
  {
    id: "perplexity-comet",
    competitor: "perplexity",
    label: "Perplexity Comet what's new",
    kind: "official_site",
    cadence: "daily",
    urls: ["https://docs.perplexity.ai/docs/resources/changelog"],
    monitoring_tier: "primary",
    parse_mode: "html",
    notes:
      "Track Perplexity changelog updates from the official docs surface when the main marketing site is challenge-protected.",
  },
  {
    id: "perplexity-blog",
    competitor: "perplexity",
    label: "Perplexity blog",
    kind: "official_site",
    cadence: "daily",
    urls: ["https://research.perplexity.ai/articles"],
    monitoring_tier: "secondary",
    parse_mode: "html",
    notes: "Track official Perplexity research and announcement-style articles from the public research site.",
  },
  {
    id: "scale-swebench-pro",
    competitor: "market",
    label: "Scale SWE-bench Pro public leaderboard",
    kind: "leaderboard",
    cadence: "daily",
    urls: ["https://labs.scale.com/leaderboard/swe_bench_pro_public"],
    monitoring_tier: "primary",
    preferred_fetch_provider: "firecrawl",
    parse_mode: "table",
    notes: "Track coding-agent leaderboard movement on the public SWE-bench Pro surface.",
  },
  {
    id: "livebench",
    competitor: "market",
    label: "LiveBench leaderboard",
    kind: "leaderboard",
    cadence: "daily",
    urls: ["https://livebench.ai/"],
    monitoring_tier: "secondary",
    parse_mode: "table",
    notes: "Track broad capability leaderboard movement from LiveBench.",
  },
  {
    id: "lmarena",
    competitor: "market",
    label: "LMSYS Arena leaderboard",
    kind: "leaderboard",
    cadence: "daily",
    urls: ["https://lmarena.ai/leaderboard"],
    monitoring_tier: "secondary",
    parse_mode: "table",
    notes: "Track public preference leaderboard movement from LMSYS Arena.",
  },
  {
    id: "artificial-analysis",
    competitor: "market",
    label: "Artificial Analysis benchmark dashboard",
    kind: "leaderboard",
    cadence: "daily",
    urls: ["https://artificialanalysis.ai/"],
    monitoring_tier: "secondary",
    parse_mode: "table",
    notes: "Track vendor/model benchmark comparisons on Artificial Analysis.",
  },
  {
    id: "llm-stats",
    competitor: "market",
    label: "LLM Stats benchmark index",
    kind: "leaderboard",
    cadence: "daily",
    urls: ["https://llm-stats.com/benchmarks"],
    monitoring_tier: "primary",
    preferred_fetch_provider: "firecrawl",
    parse_mode: "markdown",
    notes:
      "Track cross-benchmark references, vendor/model visibility, and supporting benchmark context without forcing numeric score claims when the page is index-like.",
  },
  {
    id: "openai-baseline",
    competitor: "openai",
    label: "OpenAI product and pricing baseline",
    kind: "openai_baseline",
    cadence: "daily",
    urls: [
      "https://developers.openai.com/api/docs/changelog",
      "https://openai.com/news/rss.xml",
      "https://api.openai.com/v1/models",
    ],
    monitoring_tier: "primary",
    preferred_fetch_provider: "firecrawl",
    parse_mode: "markdown",
    notes:
      "Track the OpenAI API docs changelog, public announcement feed, and model lineup using official automation-safe endpoints.",
  },
  {
    id: "community-buzz",
    competitor: "market",
    label: "Community buzz: Reddit and GitHub",
    kind: "reddit",
    cadence: "daily",
    urls: [
      "https://www.reddit.com/r/LocalLLaMA/top/.json?limit=50",
      "https://www.reddit.com/r/singularity/top/.json?limit=50",
      "https://www.reddit.com/r/artificial/top/.json?limit=50",
      "https://www.reddit.com/r/LLM/top/.json?limit=50",
    ],
    subreddits: ["LocalLLaMA", "singularity", "artificial", "LLM"],
    githubRepos: [
      "anthropics/anthropic-sdk-typescript",
      "anthropics/anthropic-cookbook",
      "googleapis/js-genai",
      "google-gemini/gemini-cli",
    ],
    monitoring_tier: "secondary",
    parse_mode: "feed",
    notes:
      "Track top community posts and repo momentum, while treating Reddit speculation as lower-confidence evidence.",
  },
];

export function getSourceById(sourceId: string) {
  const source = SOURCE_REGISTRY.find((entry) => entry.id === sourceId);
  if (!source) {
    throw new Error(`Unknown source: ${sourceId}`);
  }

  return source;
}
